# Generated by Django 4.0.3 on 2022-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_ticker', models.CharField(max_length=10)),
                ('asset_name', models.CharField(blank=True, max_length=20, null=True)),
                ('market', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetsOHLCV',
            fields=[
                ('candle_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_ticker_identification', models.IntegerField()),
                ('asset_ticker', models.CharField(blank=True, db_column='asset_ticker', max_length=9, null=True)),
                ('timeframe', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField()),
                ('open', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_ohlcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetrics',
            fields=[
                ('strat_parameters_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_end_date', models.DateTimeField()),
                ('period_start_date', models.DateTimeField()),
                ('timeframe', models.CharField(max_length=5)),
                ('strategy_params', models.CharField(max_length=300)),
                ('total_realized_r', models.DecimalField(blank=True, db_column='total_realized_R', decimal_places=3, max_digits=6, null=True)),
                ('strike_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('num_trades', models.IntegerField(blank=True, null=True)),
                ('avg_hold_time', models.IntegerField(blank=True, null=True)),
                ('expectancy', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('avg_winner', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('avg_loser', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('largest_winner', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('largest_loser', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('max_drawdown', models.IntegerField(blank=True, null=True)),
                ('max_drawup', models.IntegerField(blank=True, null=True)),
                ('winners_avg_mae', models.DecimalField(blank=True, db_column='winners_avg_MAE', decimal_places=3, max_digits=6, null=True)),
                ('winners_avg_mfe', models.DecimalField(blank=True, db_column='winners_avg_MFE', decimal_places=3, max_digits=6, null=True)),
                ('losers_avg_mfe', models.DecimalField(blank=True, db_column='losers_avg_MFE', decimal_places=3, max_digits=6, null=True)),
                ('losers_avg_mae', models.DecimalField(blank=True, db_column='losers_avg_MAE', decimal_places=3, max_digits=6, null=True)),
                ('winners_std_dev_mae', models.DecimalField(blank=True, db_column='winners_std_dev_MAE', decimal_places=3, max_digits=6, null=True)),
                ('winners_std_dev_mfe', models.DecimalField(blank=True, db_column='winners_std_dev_MFE', decimal_places=3, max_digits=6, null=True)),
                ('losers_std_dev_mae', models.DecimalField(blank=True, db_column='losers_std_dev_MAE', decimal_places=3, max_digits=6, null=True)),
                ('losers_std_dev_mfe', models.DecimalField(blank=True, db_column='losers_std_dev_MFE', decimal_places=3, max_digits=6, null=True)),
                ('number_of_bars', models.IntegerField(blank=True, null=True)),
                ('returns_to_asset_corr', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('equity_curve_regression_slope', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('equity_curve_regression_std_error', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('kelly_criterion', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('trades_list', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_reference', models.CharField(max_length=40)),
                ('strategy_name', models.CharField(blank=True, max_length=40, null=True)),
                ('strategy_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'strategies',
                'managed': False,
            },
        ),
    ]
